---
title: "Hands-on Exercise 2: Choropeth Mapping with R"
execute:
  warning: False  # This turns off warning messages being displayed
date: 8 January, 2024
date-modified: "last-modified"
---

Thematic mapping involves the use of map symbols to visualize selected properties of geographic features that are not naturally visible, such as population, temperature, crime rate, and property prices, just to mention a few of them.

Geovisualization, on the other hand, works by providing graphical ideation to render a place, a phenomenon or a process visible, enabling human's most powerful information-processing abilities - those of spatial cognition associated with our eye-brain vision system - to be directly brought to bear.

In this chapter, you will learn how to plot functional and truthful choropleth maps by using R package called **tmap** package.

# Getting Started

## Installing and loading R packages

In this section, we will use:

-   `tmap`

-   `readr` for importing delimited text file

-   `tidyr` for tidying data

-   `dplyr` for wrangling data

-   `sf` for handling geospatial data

```{r}
pacman::p_load(sf, tmap, tidyverse)
```

# Importing Data

Two data set will be used to create the Choropeth map.

-   Master Plan 2014 Subzone Boundary (Web) (i.e. `MP14_SUBZONE_WEB_PL`)

    -   ESRI shapefile format (Geospatial data)

    -   Downloaded from [data.gov.sg](https://data.gov.sg)

    -   Consists of the geographical boundary of Singapore at the planning subzone level.

    -   The data is based on URA Master Plan 2014

-   Singapore Residents by Planning Area / Subzone, Age Group, Sex and Type of Dwelling, June 2011-2020 (i.e. `respopagesextod2011to2020.csv`)

    -   CSV format (Aspatial data)

    -   Downloaded from [Department of Statistics, Singapore](https://singstat.gov.sg)

    -   Although it does not contain any coordinate values, it's PA and SZ fields can be used as unique identifiers to geocode to `MP14_SUBZONE_WEB_PL` shapefile.
